#!/usr/bin/env python

from mr_shed_output import output, init
import time
import sys
import datetime
import os
from ConfigParser import SafeConfigParser

# CONFIG
config = SafeConfigParser()
config.read(os.path.dirname(os.path.realpath(__file__)) + '/config.ini')

# FUNCTION DEFS
def log(msg):
	now = datetime.datetime.now()
	str = now.strftime("%Y-%m-%d %H:%M") + " >> " + msg
	print str
	open(config.get('logging','log_file'),"a").write(str + "\n")

###############
# RUN-TIME
###############

log("Initialising sprinkler system")

init()

# output(1, 'off')
output(2, 'off')
output(3, 'off')
output(4, 'off')

log("Init complete, everything should be off")

sys.stdout.flush()
sys.exit(0);
