#!/usr/bin/env python

from mr_shed_output import output, init
import time
import sys
import datetime
import os
from ConfigParser import SafeConfigParser

# CONSTANTS
OUTPUT_NUM_MAP = {
	"lawn": 2,
	"garden_a": 3,
	"garden_b": 4,
}


# CONFIG
config = SafeConfigParser()
config.read(os.path.dirname(os.path.realpath(__file__)) + '/config.ini')

# FUNCTION DEFS
def log(msg):
	now = datetime.datetime.now()
	str = now.strftime("%Y-%m-%d %H:%M") + " >> " + msg
	print str
	open(config.get('logging','log_file'),"a").write(str + "\n")


###############
# RUN-TIME
###############

init()

# ARGUMENTS
if (len(sys.argv) != 3):
	print "Invalid number of arguments"
	print "Should be ./sprinkler ZONE ACTION"
	sys.exit()

zone = str(sys.argv[1])
action = str(sys.argv[2])

if (zone == 'all'):
	if (action == 'on'):
		print "Invalid, cannot turn on all zones, only turn all off"
	elif (action == 'off'):
		log("Turning ALL sprinklers OFF")
		# output(1,'off')
		output(2,'off')
		output(3,'off')
		output(4,'off')
	else:
		print "Invalid action \"" + action + "\""
elif zone in OUTPUT_NUM_MAP:
	log("Turning " + zone.upper() + " sprinklers " + action.upper())
	output(OUTPUT_NUM_MAP[zone], action)
		
else:
	# Invalid zone
	print "Invalid zone \"" + zone + "\""

sys.stdout.flush()
